config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users

  get '/auth/failure' => 'omniauth_callbacks#failure'
  root 'home#welcome'
  get 'dashboard', to: 'home#dashboard', as: :dashboard
  get 'about', to: 'home#about', as: :about
  get 'market_place', to: 'alpacas#market_place', as: :market_place
  # put 'change_owner', to: "ownerships#change_owner", as: :change_
  resources :alpacas do
    put :update, on: :member
  end

  resources :alpacas
  resources :events
  # resources :ownerships


  resources :ownerships do
    put :change_owner, on: :member
  end
end

app/views/layouts/shared/_carousel.html.haml
.row
  .col.md-12
    .carousel#dashboard-carousel.slide.backgrounds-carousel{ data: { ride: 'slide' }}
      .carousel-inner
        - (1..3).each do |i|
          .carousel-item{ class: "#{i == 1 ? 'active' : ''}" }
            .d-block.background-slide{ class: "background-slide-#{i}" }
              .carousel-caption.d-none.d-md-block
      %a.carousel-control-prev{ href: '#dashboard-carousel', role: 'button', data: { slide: 'prev' }}
        %span.carousel-control-prev-icon{ 'aria-hidden' => 'true'}
        %span.sr-only Previous
      %a.carousel-control-next{ href: '#dashboard-carousel', role: 'button', data: { slide: 'next' }}
        %span.carousel-control-next-icon{ 'aria-hidden' => 'true'}
        %span.sr-only Next
    

app/views/layouts/shared/_footer.html.haml
%footer.footer
  .container
    .about.pull-left
      = link_to 'About', root_path

app/views/layouts/shared/_logo.html.haml
= link_to root_path, class: 'logo' do
    = image_tag 'alpaca_logo.png', :height => "20", :width => "20"

app/views/layouts/shared/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/shared/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-secondary
  .container
    %a.navbar-brand{ href: root_path }
      = image_tag 'alpaca_logo_transparent.png', class: 'navbrand-logo-image'
      = link_to "Alpaca Game", root_path, class: 'navbar-brand'
    #navbar.navbar-collapse.collapse
      %ul.navbar-nav.mr-auto

      %ul.nav.navbar-nav.ml-auto
        - if user_signed_in?
          %li.nav-item
            = link_to "About Alpaca", about_path, class: 'nav-link'
          %li.nav-item
            = link_to "Alpacas", alpacas_path, class: 'nav-link'
          %li.nav-item
            = link_to "Events", events_path, class: 'nav-link'
          %li.nav-item
            = link_to "Market", market_place_path, class: 'nav-link'
          %li.nav-item
            = link_to "#{current_user.fortune}", user_path(current_user), class: 'nav-link'
          %li.nav-item
            = image_tag("hay.png", :alt => "hay", size: "20x20")

          .dropdown.show
            %a#dropdown-menu-link.btn.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.email
            .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "dropdown-menu-link"}
              = link_to t('navbar.logout'), destroy_user_session_path, method: :delete, class: 'dropdown-item'
              = link_to t('navbar.edit_profile'), edit_user_registration_path, class: 'dropdown-item'
        - else
          %li.nav-item.btn_margin
            = link_to t('navbar.signin'), new_user_session_path, class: 'nav-link', class: 'btn btn-outline-light'
          %li.nav-item.btn_margin
            = link_to t('navbar.signup'), new_user_registration_path, class: 'nav-link', class: 'btn btn-outline-light'