config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users

  get '/auth/failure' => 'omniauth_callbacks#failure'
  root 'home#welcome'
  get 'dashboard', to: 'home#dashboard', as: :dashboard
  get 'about', to: 'home#about', as: :about
  get 'market_place', to: 'alpacas#market_place', as: :market_place
  # put 'change_owner', to: "ownerships#change_owner", as: :change_
  resources :alpacas do
    put :update, on: :member
  end

  resources :alpacas
  resources :events
  # resources :ownerships


  resources :ownerships do
    put :change_owner, on: :member
  end
end

app/models/alpaca.rb
# frozen_string_literal: true

class Alpaca < ApplicationRecord
  validates :name,
            :quote,
            :picture_url,
            :price,
            presence: true

  has_many :alpaca_skills
  has_many :skills, through: :alpaca_skills

  has_many :alpaca_events
  has_many :events, through: :alpaca_events

  has_many :ownerships
  has_many :users, through: :ownerships

  def current_owner
    ownerships.where(owner_to: nil).pluck(:user_id)
  end
end

app/controllers/alpacas_controller.rb
# frozen_string_literal: true
class AlpacasController < ApplicationController
  before_action :find_alpaca, only: %i[show update]

  def index
    ownerships = Ownership.where(owner_to: nil, user_id: current_user)
    @alpacas = Alpaca.where(id: ownerships.map{|o|o.alpaca_id}, for_sale: false)
  end

  def new;end

  def show;end

  def market_place
    @alpacas = Alpaca.where(for_sale: true)
  end

  def update
    if !@alpaca.for_sale
      @alpaca.update_attributes(for_sale: true)
      flash[:success] = "Alpaca put on market"
      if @alpaca.update_attributes(alpaca_params)
        redirect_to alpacas_path
      else
        redirect_to alpaca_path(@alpaca)
      end
    else
      @alpaca.update_attributes(for_sale: false)
      redirect_to market_place_path
    end
  end


  private

  def alpaca_params
    params.require(:alpaca).permit(:for_sale, :price)
  end
  def find_alpaca
    @alpaca = Alpaca.find(params[:id])
  end
end

app/helpers/alpacas_helper.rb
# frozen_string_literal: true

module AlpacasHelper
end

app/views/alpacas/_button.html.haml
- if @alpaca.current_owner.include?(current_user.id) && @alpaca.for_sale
  = link_to 'Cancel the sale', @alpaca.toggle(:for_sale), method: :put, class: 'btn btn-secondary btn-lg'
- elsif @alpaca.for_sale
  = link_to 'Buy Alpaca', change_owner_ownership_path, method: :put, class: 'btn btn-success btn-lg'

app/views/alpacas/_listing.html.haml
.card-deck
  - @alpacas.each do |alpaca|
    .col-3
      .card
        = link_to alpaca_path(alpaca) do
          %img.card-img-top{:alt => "#{alpaca.name}", :src => "#{alpaca.picture_url}"}/
          .card-body
            %h5.card-title="#{alpaca.name}"
            %p.card-text="Personal motto: #{alpaca.quote}"

app/views/alpacas/_sellform.html.haml
= simple_form_for @alpaca do |f|
  = f.input :price, label: 'How much hay do you want?', required: true, error: "Don't be so generous. Enter some price ;)"
  = f.button :submit, "Sell Alpaca", class: 'btn btn-success btn-lg'

app/views/alpacas/index.html.haml
%h1 My alpacas
= render 'listing'

app/views/alpacas/market_place.html.haml
%h1 Alpacas looking for new home
= render 'listing'

app/views/alpacas/new.html.erb
<p> New Alpaca here </p>

app/views/alpacas/show.html.haml
.row
  .col-12
    %h1 #{@alpaca.name}
  .col-4
    %img.img-thumbnail{:alt => "Avatar", :src => "#{@alpaca.picture_url}"}
  .col-8
    %p="Gender: #{convert_gender(@alpaca)}"
    %p Favorite quote: #{@alpaca.quote}
    %p
    - get_alpaca_skills(@alpaca).each do |skill_name, value|
      %p="#{skill_name}: #{value}"

    %p
    %p
      - if @alpaca.for_sale
        ="Price: #{@alpaca.price}"
        = image_tag("hay.png", :alt => "hay", size: "20x20")
    %p
    %p
    %p
      - if @alpaca.current_owner.include?(current_user.id) && !@alpaca.for_sale
        =render 'sellform'
      - else
        =render 'button'