config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users

  get '/auth/failure' => 'omniauth_callbacks#failure'
  root 'home#welcome'
  get 'dashboard', to: 'home#dashboard', as: :dashboard
  get 'about', to: 'home#about', as: :about
  get 'market_place', to: 'alpacas#market_place', as: :market_place
  # put 'change_owner', to: "ownerships#change_owner", as: :change_
  resources :alpacas do
    put :update, on: :member
  end

  resources :alpacas
  resources :events
  # resources :ownerships


  resources :ownerships do
    put :change_owner, on: :member
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :authenticate_user!

  def welcome; end

  def dashboard; end

  def about; end
end

app/views/home/about.html.haml
.jumbotron
  %h1.display-4 Three things about alpacas you always wanted to know but was afraid to ask.
  %h4 Alpacas! They’re fluffy, they’re good-natured, their hair can make super-soft sweaters and they’re really cute. But alpacas are more than just a furry face.
  %hr.my-4/
  
  %ol
    %li
      %h6 They’re historical
      %p Alpacas were raised by the Incas in South America over 6000 years ago. Kept in herds, Alpacas made their dainty way among the mountains of Peru, Chile and Bolivia, where clothing made from their hair was reserved for Incan royalty.
    %li
      %h6 They come in 2 types
      %p Alpacas come in all sorts of colours, but there are actually only two types of breeds. The difference is in the hair. The Huacaya alpacas have a really fluffy fleece that gives them the appearance of teddy bears, while the Suri type have long locks of hair that grow straight down. Most alpacas that you see in Canada are Huacayas.
    %li
      %h6 Super-hair
      %p Alpacas get shaved for their hair, just like sheep. And just like sheep, all sorts of things can be made from their wool, like sweaters and hats and scarves and blankets. Unlike sheep’s wool, alpaca hair is hypoallergenic, which means people won’t get allergies from it and sneeze and itch. Even better, alpaca wool is flame-resistant and water-resistant. Which means you can have a lot of adventures in your alpaca sweater – that, and it’s easy to clean.
 

app/views/home/dashboard.html.haml
.card-deck
  .row
    .card
      = link_to alpacas_path do
        %img.card-img-top{:alt => "Alpacas", :src => "https://static1.squarespace.com/static/58a9a29f2e69cf0bf2bb9395/t/5a2c21d2f9619a9e280b379d/1512841687721/alpaca.jpg?format=750w"}/
        .card-body
          %h5.card-title My Alpacas
          %p.card-text All your Alpacas in one place

    .card
      = link_to events_path do
        %img.card-img-top{:alt => "Events", :src => "https://www.openherd.com/userPhotos/Large/2012_634614480374350000.jpg"}/
        .card-body
          %h5.card-title Events
          %p.card-text Compete with other Alpacas, get eternal glory!

    .card
      = link_to user_path(current_user) do
        %img.card-img-top{:alt => "Profile", :src => "https://static3.therichestimages.com/wordpress/wp-content/uploads/2017/11/Redneck-Olympic-Torch.jpg"}/
        .card-body
          %h5.card-title My profile
          %p.card-text Take a look at your profile, or edit it

    .card
      = link_to market_place_path do
        %img.card-img-top{:alt => "Market", :src => "https://www.travelcake.net/wp-content/uploads/2016/06/ANIMAL1.jpg"}/
        .card-body
          %h5.card-title Alpaca Market
          %p.card-text Trade Alpacas with other players

app/views/home/welcome.html.haml
.jumbotron
  %h1.display-4 Welcome in our fabulous Alpaca World!
  %p.lead In this amazing browser game, you can keep your own Alpacas, train them, and compete with other players in sport events for alpacas.
  %hr.my-4/
  %p Are you ready for outstanding Alpaca adventure?
  = link_to 'Ohhhh yes!!!', dashboard_path, class: 'btn btn-primary btn-lg'
  = link_to 'Umm... Not really...', destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-lg'