config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users

  get '/auth/failure' => 'omniauth_callbacks#failure'
  root 'home#welcome'
  get 'dashboard', to: 'home#dashboard', as: :dashboard
  get 'about', to: 'home#about', as: :about
  get 'market_place', to: 'alpacas#market_place', as: :market_place
  # put 'change_owner', to: "ownerships#change_owner", as: :change_
  resources :alpacas do
    put :update, on: :member
  end

  resources :alpacas
  resources :events
  # resources :ownerships


  resources :ownerships do
    put :change_owner, on: :member
  end
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates :name,
            :description,
            presence: true

  has_many :alpaca_events
  has_many :alpacas, through: :alpaca_events
  belongs_to :category
  belongs_to :user
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    @events = Event.where.not(user_id: current_user.id)
                   .joins(:alpacas)
                   .group('events.id')
                   .having('count(alpaca_id) < 2')
  end

  def show
    @event = Event.find(params[:id])
    @alpacas = @event.alpacas
    ownerships = Ownership.where(owner_to: nil, user_id: current_user.id)
    @alpacas_to_choose = Alpaca.where(id: ownerships.map{|o|o.alpaca_id}, for_sale: false)
    @winner = @event.alpaca_events.find_by(winner: true)&.alpaca
  end

  def new
    @event = Event.new
    ownerships = Ownership.where(owner_to: nil, user_id: current_user.id)
    @alpacas = Alpaca.where(id: ownerships.map{|o|o.alpaca_id}, for_sale: false)
  end

  def create
    @event = current_user.events.new(event_params)
    @alpaca = current_user.alpacas.find(params[:event][:alpacas])

    if @event.save
      @event.alpacas << @alpaca
      redirect_to @event
    else
      render 'new'
    end
  end

  def update
    @alpaca = Alpaca.find(params[:event][:alpacas])
    @event = Event.find(params[:id])

    if @event.alpacas << @alpaca
      @points = CalculateEventPointsAndAssignToAlpacas.new(@event).call
      @winner = Alpaca.find(@points.max_by{ |_alpaca_id, points| points }.first)
      @skillup = AlpacaSkill.find_by(alpaca_id: @winner.id, skill_id: @event.category.category_skills.first.skill_id)
      @skillup.update_attributes(level: @skillup.level + 5)
      @event.alpaca_events.find_by(event_id: @event.id, alpaca_id: @points.max_by{ |_alpaca_id, points| points })
            .update(winner: true)

      redirect_to @event
    else
      render 'update'
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :category_id)

  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  def host?(user, event)
    event.user == user
  end

  def button_visible?(user, event, winner)
    !host?(user, event) && !winner
  end

  def convert_gender(alpaca)
    return 'Male'   if     alpaca.gender
    return 'Female' unless alpaca.gender
  end

  def get_alpaca_points(alpaca, event)
    alpaca.alpaca_events.find_by(event_id: event.id)&.points
  end

  def get_alpaca_skills(alpaca)
    skills = {}

    alpaca.alpaca_skills.each do |alpaca_skill|
      skill = Skill.find(alpaca_skill.skill_id)
      skills[skill.name] = alpaca_skill.level
    end

    skills
  end
end

app/views/events/_alpaca_card.html.haml
.col-4
  .card.event-card
    = link_to alpaca_path(alpaca) do
      %img.card-img-top{:alt => "#{alpaca.name}", :src => "#{alpaca.picture_url}"}/
      .card-body
        %h4.card-title="#{alpaca.name}"
        %h5.card-text="Skills:"
        - get_alpaca_skills(alpaca).each do |skill_name, value|
          %p="#{skill_name}: #{value}"

app/views/events/_form.html.haml
= simple_form_for @event do |f|
  = f.input :name
  = f.input :description
  = f.association :category
  = f.input :alpacas, collection: @alpacas
  = f.submit "Create event", class: "btn btn-primary col-centered"

app/views/events/_listing.html.haml
.card-deck
  - events.each do |event|
    .col-4
      .card
        = link_to event_path(event) do
          .card-body
            %img.card-img-top{:alt => "#{event.category.name}", :src => "#{event.category.picture_url}"}/
            %h5.card-title="#{event.name}"
            %p.card-text="Description: #{event.description}"
            %p.card-text="Category: #{event.category.name}"

app/views/events/index.html.haml
%br
%br
.col-3.col-centered
  .add_button
    = link_to 'Add event', new_event_path, method: :get, class: 'btn btn-info btn-lg btn-block'

.events-container
  %h1 My events
  = render 'listing', events: current_user.events
  %h1 Available events
  - unless @events.empty?
    = render 'listing', events: @events
  - else
    %h3 No events?! How it's possible?! You'd better add something!

app/views/events/new.html.haml
= render 'form'

app/views/events/show.html.haml
.card-deck
  = render 'alpaca_card', alpaca: @alpacas.first
  .card.blank-card
  = @alpacas.second ? (render 'alpaca_card', alpaca: @alpacas.second) : ''

.versus
  VS

- if button_visible?(current_user, @event, @winner)
  .col-2.col-centered
    .fixed-button
      = simple_form_for @event do |f|
        = f.input :alpacas, collection: @alpacas_to_choose
        = f.submit "Join event", class: "btn btn-primary"

- if @winner
  .row
    .col-12.winner-display
      %h3 The winner is #{@winner.name}!
  .row
    .col-12.points-display
      - @alpacas.each do |alpaca|
        #{alpaca.name} got #{get_alpaca_points(alpaca, @event)} points.
        %br